// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWU_tnt60ZXR8wghyPASWGbknCLs1rXs',
    appId: '1:37481550434:web:454d4631e16b548adc373b',
    messagingSenderId: '37481550434',
    projectId: 'stable-horde-flutter',
    authDomain: 'stable-horde-flutter.firebaseapp.com',
    storageBucket: 'stable-horde-flutter.appspot.com',
    measurementId: 'G-4VFRG9980C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ZnDU9ZJ3PPaJdVhOLiFJw3hEdKG9H7c',
    appId: '1:37481550434:android:b81fcfb872dc4a72dc373b',
    messagingSenderId: '37481550434',
    projectId: 'stable-horde-flutter',
    storageBucket: 'stable-horde-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNTPD7l2hXxRv3PILxxd4kQ0flIrOQZg',
    appId: '1:37481550434:ios:94431eb35ec84beedc373b',
    messagingSenderId: '37481550434',
    projectId: 'stable-horde-flutter',
    storageBucket: 'stable-horde-flutter.appspot.com',
    iosClientId:
        '37481550434-ts8j0jihl9atjjnp0see606t394l3u1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.stableHordeFlutter',
  );
}
