// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazPRXuSwpMbFu1QeDSmfcOWsnBrLq9pg',
    appId: '1:28925556847:android:139e0e0c8a39474c39f59a',
    messagingSenderId: '28925556847',
    projectId: 'zoomscroller',
    storageBucket: 'zoomscroller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfC2jhJbaGwtLvLyWNQjaSTukGGmLpWdU',
    appId: '1:28925556847:ios:fd4ad2cfde19b93139f59a',
    messagingSenderId: '28925556847',
    projectId: 'zoomscroller',
    storageBucket: 'zoomscroller.appspot.com',
    androidClientId:
        '28925556847-nvh0a05oeqatfnti1eq6p2tj62uvnc7h.apps.googleusercontent.com',
    iosClientId:
        '28925556847-ecd2o8rtol21bst0cj1ddbqhbkpd9ere.apps.googleusercontent.com',
    iosBundleId: 'com.nicd.zoomscroller',
  );
}
