# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Firebase app distribution"
  lane :alpha do
    sh "flutter build apk --release"

    firebase_app_distribution(
        app: "1:28925556847:android:139e0e0c8a39474c39f59a",
        groups: "alpha_testers",
        firebase_cli_token: "1//065DnfJZkaeizCgYIARAAGAYSNwF-L9Irmfx-bA5c91d8d4rQUv-M79zmJN8WZTgos48VHqPxvrLIhL1j5c5fILj3ONZTAqIiqLQ",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

end